version: "3"
services:
  elasticsearch-knock-knock:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.9.2
    container_name: elasticsearch-knock-knock
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
  kibana-knock-knock:
    image: docker.elastic.co/kibana/kibana-oss:7.9.2
    container_name: kibana-knock-knock
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch-knock-knock:9200
    ports:
      - 5601:5601
  loader-knock-knock:
    build: ./loader
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch-knock-knock:9200
    depends_on:
      - elasticsearch-knock-knock
      - kibana-knock-knock
